# Generated by Django 4.2 on 2026-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Assistant Treasurer', 'Assistant Treasurer'), ('Organizing Secretary', 'Organizing Secretary'), ('Assistant Organizing Secretary', 'Assistant Organizing Secretary'), ('Media & Publication Secretary', 'Media & Publication Secretary'), ('Assistant Media & Publication Secretary', 'Assistant Media & Publication Secretary'), ('Executive Member', 'Executive Member'), ('Member', 'Member')], max_length=50),
        ),
    ]
