# Generated by Django 4.2 on 2026-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0002_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EEE', 'Electrical & Electronic Engineering'), ('CE', 'Civil Engineering'), ('BBA', 'Business Administration'), ('LAW', 'Law')], default='CSE', max_length=20),
        ),
    ]
