# Generated by Django 4.2 on 2026-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0004_alter_member_bio_alter_member_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
