# Generated by Django 4.2 on 2026-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VP", "0012_remove_panel_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="expertise",
            field=models.TextField(blank=True, help_text="Describe advisor expertise areas"),
        ),
    ]
