# Generated by Django 4.2 on 2026-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VP", "0013_advisor_expertise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="expertise",
            field=models.TextField(
                blank=True,
                help_text="Enter one expertise per line (bullet points are optional)",
            ),
        ),
    ]
