# Generated by Django 4.2 on 2026-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0014_alter_advisor_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
