# Generated by Django 4.2 on 2026-04-09 00:00

from django.db import migrations, models


def seed_existing_userprofiles(apps, schema_editor):
    UserProfile = apps.get_model("VP", "UserProfile")
    UserProfile.objects.all().update(
        payment_method="cash",
        payment_reference="Previous panel",
    )


def unseed_existing_userprofiles(apps, schema_editor):
    UserProfile = apps.get_model("VP", "UserProfile")
    UserProfile.objects.all().update(
        payment_method="cash",
        payment_reference="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("VP", "0017_alter_eventresult_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("bkash", "Bkash Payment")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(seed_existing_userprofiles, unseed_existing_userprofiles),
    ]
