# Generated by Django 4.2 on 2026-04-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0019_userprofile_is_bars_member_userprofile_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_reference',
        ),
    ]
