# Generated by Django 4.2 on 2026-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0020_remove_userprofile_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_name',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Joint Secretary', 'Joint Secretary'), ('Treasurer', 'Treasurer'), ('Assistant Treasurer', 'Assistant Treasurer'), ('Organizing Secretary', 'Organizing Secretary'), ('Assistant Organizing Secretary', 'Assistant Organizing Secretary'), ('Media & Publication Secretary', 'Media & Publication Secretary'), ('Assistant Media & Publication Secretary', 'Assistant Media & Publication Secretary'), ('Executive Member', 'Executive Member'), ('General Member', 'General Member')], max_length=60, null=True),
        ),
    ]
