# Generated by Django 4.2 on 2026-04-17 09:56

from django.db import migrations, models


def create_default_application(apps, schema_editor):
    GeneralMemberApplication = apps.get_model("VP", "GeneralMemberApplication")
    GeneralMemberApplication.objects.get_or_create(
        title="Apply for General Member of BARS",
        defaults={
            "form_url": "",
            "is_active": False,
        },
    )


def delete_default_application(apps, schema_editor):
    GeneralMemberApplication = apps.get_model("VP", "GeneralMemberApplication")
    GeneralMemberApplication.objects.filter(
        title="Apply for General Member of BARS"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0021_alter_userprofile_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Apply for General Member of BARS', max_length=120)),
                ('form_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'General Member Application',
                'verbose_name_plural': 'General Member Application',
            },
        ),
        migrations.RunPython(create_default_application, delete_default_application),
    ]
