# Generated by Django 4.2 on 2026-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0024_event_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank or set to null for unlimited seats.', null=True),
        ),
    ]
