# Generated by Django 4.2 on 2026-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0026_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='hand_cash_recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('hand_cash', 'Hand Cash')], default='hand_cash', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/photos/'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
