# Generated by Django 4.2 on 2026-06-23 05:21

from django.db import migrations, models

def populate_serial_numbers(apps, schema_editor):
    EventRegistration = apps.get_model('VP', 'EventRegistration')
    Event = apps.get_model('VP', 'Event')
    for event in Event.objects.all():
        # Order by registered_at then by id to ensure deterministic sequence
        registrations = EventRegistration.objects.filter(event=event).order_by('registered_at', 'id')
        for i, reg in enumerate(registrations, start=1):
            reg.serial_no = i
            reg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0027_eventregistration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_serial_numbers, reverse_code=migrations.RunPython.noop),
    ]
