# Generated by Django 4.2 on 2026-06-23 06:03

from django.db import migrations, models

def set_existing_statuses_approved(apps, schema_editor):
    EventRegistration = apps.get_model('VP', 'EventRegistration')
    EventRegistration.objects.filter(serial_no__isnull=False).update(status='Approved')

class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0028_eventregistration_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.RunPython(set_existing_statuses_approved, reverse_code=migrations.RunPython.noop),
    ]
