# Generated by Django 4.2 on 2026-06-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0029_eventregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/'),
        ),
    ]
