# Generated by Django 4.2 on 2026-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0030_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='segments',
            field=models.TextField(blank=True, help_text='Enter segments separated by commas (e.g. LFR, RoboSoccer). Only applicable if segments are available.'),
        ),
        migrations.AddField(
            model_name='event',
            name='segments_available',
            field=models.BooleanField(default=False, verbose_name='Segment available'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
