# Generated by Django 4.2 on 2026-08-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0031_event_segments_event_segments_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='segments',
            field=models.TextField(blank=True, help_text='Enter segments separated by commas (e.g. LFR:50, RoboSoccer:30). If a segment has unlimited seats, just write the name (e.g. LFR). Only applicable if segments are available.'),
        ),
    ]
