# Generated by Django 4.2 on 2026-08-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0032_alter_event_segments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
    ]
