# Generated by Django 4.2 on 2026-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VP', '0033_alter_eventregistration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/id_cards/'),
        ),
    ]
